plugin_blacklist:
# common
# actuator_control
- ftp
- safety_area
# extras
# altitude
- debug_value
- image_pub
- px4flow
- vibration
- vision_speed_estimate
- wheel_odometry
- waypoint
- vision_pose_estimate
- wheel_odometry
- vfr_hud
- trajectory
- terrain
- guided_target
- camera
- home_position
- distance_sensor
- param
- tunnel
- rallypoint
- setpoint_trajectory
- play_tune
#- rangefinder

#controller
#- guided_target
#- setpoint_velocity
#- setpoint_position
#- setpoint_raw
#- setpoint_attitude

plugin_whitelist: []
